### ISSUE TITLE
Expresiones Booleanas.

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/expresiones-boolenas-equipo#1]
[Practica de expresiones booleanas .pdf](https://github.com/SistemasTecTlaxiaco/expresiones-boolenas-equipo/files/7729827/Practica.de.expresiones.booleanas.pdf)

**Comment by Arlet04** [comment]
Portada (Notable): Falto agregar los logotipos de la institución 22 puntos
Procedimiento (Notable): Faltó agregar los materiales que ocuparon para la realización de la práctica 22 puntos
Figuras, ilustraciones y fotografías (Excelente): 25 puntos
Resultados y conclusiones (Notable) : Faltó describir los resultados obtenidos de la práctica 22 puntos
Total: 91/100
Calificación: 18%

**Comment by Arlet04** [comment]
Portada (Notable): Falto agregar los logotipos de la institución 22 puntos
Procedimiento (Notable): Faltó agregar los materiales que ocuparon para la realización de la práctica 22 puntos
Figuras, ilustraciones y fotografías (Excelente): 25 puntos
Resultados y conclusiones (Notable) : Faltó describir los resultados obtenidos de la práctica 22 puntos
Total: 91/100
Calificación: 27%

**Comment by josealfredo79** [comment]
Si esta bien hecho y revisado
